ScanConfig defaults no longer sort results
anza-xyz/agave pull request #1539
Opened 2024-05-30 12:30 UTC by godmodegalactus

#### Problem

Currently ScanConfig::default sets collect_unsorted to false which has a huge performance impact.
We spend too much time to sort the results when we really do not need to sort the results.

This change will improve performance by x2-x3 for large results.

#### Summary of Changes

Change the default to not sort results.

2024-05-31 13:15 UTC, brooksprumo reviewed
Seems reasonable to me overall.

@CriesofCarrots Can you take a look too, please? Do you know if the CLI/RPC output changes will impact user expectations?

2024-05-31 13:15 UTC, brooksprumo commented on accounts-db/src/accounts_index.rs
> -#[derive(Debug, Default)]
IMO I think it's both common—idiomatically speaking—and expected to have `Default` implemented on a Config-like type.

I think I'm in favor of manually implementing `Default` and setting `collect_all_unsorted` to true.

2024-05-31 17:23 UTC, CriesofCarrots commented
> @CriesofCarrots Can you take a look too, please? Do you know if the CLI/RPC output changes will impact user expectations?

I see the usages in `rpc.rs` have already been updated to use `ScanConfig::new(!RpcProgramAccountsConfig::sort_results)`. It looks like the non_circulating_supply results in rpc could change, as well as the results in solana_rpc_client (due to usage of `RpcProgramAccountsConfig::default()`). But we don't make any guarantees about ordering in RPC responses with account scan results, so I think this is okay.

The one place we might want to preserve existing behavior is in agave_ledger_tool. While I assume most engineers are not making assumptions about account order, it might be a little annoying for the default to change, or at least have no way to get sorted results (especially for TestValidator usage where the number of accounts is small). Could we preserve sorted in that bin in this PR? We could add cli configuration for `--sorted` and change the default in a follow-up.

2024-06-03 12:50 UTC, godmodegalactus commented on accounts-db/src/accounts_index.rs
> -#[derive(Debug, Default)]
Ok I will update to default.

2024-06-04 08:41 UTC, godmodegalactus commented
> > @CriesofCarrots Can you take a look too, please? Do you know if the CLI/RPC output changes will impact user expectations?
> 
> I see the usages in `rpc.rs` have already been updated to use `ScanConfig::new(!RpcProgramAccountsConfig::sort_results)`. It looks like the non_circulating_supply results in rpc could change, as well as the results in solana_rpc_client (due to usage of `RpcProgramAccountsConfig::default()`). But we don't make any guarantees about ordering in RPC responses with account scan results, so I think this is okay.
> 
> The one place we might want to preserve existing behavior is in agave_ledger_tool. While I assume most engineers are not making assumptions about account order, it might be a little annoying for the default to change, or at least have no way to get sorted results (especially for TestValidator usage where the number of accounts is small). Could we preserve sorted in that bin in this PR? We could add cli configuration for `--sorted` and change the default in a follow-up.

Ok for now by default all ledger tool will use sorted : true. Will add the option in another PR.
Restoring the ScanConfig::Default with value for collect_unsorted = true.
Minor change adding sort_results for get_large_accounts method.

2024-06-11 12:43 UTC, brooksprumo requested changes
Overall looks good! Mostly nit changes.

Also, please update the PR title *and description*, since they are no longer accurate.

2024-06-11 12:43 UTC, brooksprumo commented on accounts-db/src/accounts.rs
> +        sorted: bool,
nit: Can this parameter be renamed to `sort_results`? Otherwise when I see this function signature I'll always end up asking my "*what* is sorted?", until I look at the implementation and remember.

This will also match the RPC function parameters.

```suggestion
        sort_results: bool,
```

Please apply this same suggestion to the other similar function parameters as well.

2024-06-11 12:43 UTC, brooksprumo commented on accounts-db/src/accounts_index.rs
> +            abort: None,
nit: This could remain `..ScanConfig::default()`. Then there's one fewer change in this PR, and one fewer spot of code duplication.

```suggestion
            ..ScanConfig::default()
```

2024-06-11 12:43 UTC, brooksprumo commented on rpc/src/rpc.rs
> +        let sorted_results = config.sort_results.unwrap_or(true);
👍 for the `.unwrap_or(true)`.

nit: Can the variable name remain unchanged though?

```suggestion
        let sort_results = config.sort_results.unwrap_or(true);
```

2024-06-11 12:43 UTC, brooksprumo commented on accounts-db/src/accounts.rs
> +    }
Looks like this new test is a duplicate of what's already in `accounts_index.rs`:

https://github.com/anza-xyz/agave/blob/0fa047ee7d4b3d726c75ccdf8c357b1cbbafc19a/accounts-db/src/accounts_index.rs#L4230-L4232

Why test it again here?

2024-06-11 12:43 UTC, brooksprumo commented on runtime/src/bank.rs
> +    pub fn get_all_accounts(&self, sorted: bool) -> ScanResult<Vec<PubkeyAccountSlot>> {
Please use `sort_results` for the parameter/variable name. Please apply this to the whole file.

```suggestion
    pub fn get_all_accounts(&self, sort_results: bool) -> ScanResult<Vec<PubkeyAccountSlot>> {
```

2024-06-13 13:08 UTC, brooksprumo requested changes

2024-06-13 13:08 UTC, brooksprumo commented on runtime/src/bank.rs
> +    pub fn scan_all_accounts<F>(&self, scan_func: F, sorted: bool) -> ScanResult<()>
Please use `sort_results` as the parameter name in the whole file.

https://github.com/anza-xyz/agave/pull/1539#discussion_r1634813302

2024-06-13 13:09 UTC, brooksprumo commented on runtime/src/bank.rs
> +    pub fn get_all_accounts(&self, sorted: bool) -> ScanResult<Vec<PubkeyAccountSlot>> {
Unresolving; this is not applied to the whole file:
https://github.com/anza-xyz/agave/pull/1539#discussion_r1638187195

2024-06-13 13:53 UTC, godmodegalactus commented on runtime/src/bank.rs
> +    pub fn scan_all_accounts<F>(&self, scan_func: F, sorted: bool) -> ScanResult<()>
thought i caught them all sorry.

2024-06-13 16:07 UTC, brooksprumo reviewed
Code looks good now, thanks!

From https://github.com/anza-xyz/agave/pull/1539#pullrequestreview-2110281678, please also update the PR description.

2024-06-14 11:37 UTC, godmodegalactus commented
I had already updated but may be there is standard of naming PR in solana which i am unware of.

2024-06-14 11:37 UTC, godmodegalactus commented
Merge at your preference.

2024-06-14 12:26 UTC, brooksprumo commented
> I had already updated but may be there is standard of naming PR in solana which i am unware of.

Here's what is says currently in the PR description: 

> Summary of Changes
>
> Instead of changing default, i removed the default and set ScanConfig::new(true) to ensure that we do not add any regessions.

This is incorrect. The default is *not* removed, it *is* changed.

I'll fix it.

2024-06-14 12:27 UTC, brooksprumo approved these changes

2024-06-14 12:27 UTC, merged