[TieredStorage] Store account address range
anza-xyz/agave pull request #172
Opened 2024-03-11 09:07 UTC by yhchiang-sol

#### Problem
The TieredStorageFooter has the min_account_address and
max_account_address fields to describe the account address
range in its file.  But the current implementation hasn't updated
the fields yet.

#### Summary of Changes
This PR enables the TieredStorage to persist address range
information into its footer via min_account_address and
max_account_address.

#### Test Plan
Updated tiered-storage test to verify persisted account address range.

2024-03-12 14:11 UTC, brooksprumo commented on accounts-db/src/tiered_storage/meta.rs
> +}
1. Please derive `Debug`
2. How about removing `_address` from the fields? They seem redundant since the type itself has "address" in the name.
3. Please add doc comments explaining what this struct is for/does. It doesn't have to be long. It's also easy to see this is a min and max. So just saying *what* the fields are is not particularly useful.
4. IMO the named lifetime of `'address` is not helpful. The lifetime is coming from the `StorableAccountsWithHashesAndWriteVersions`. I think a simple `'a` is fine here.
5. If the lifetimes are annoying, an alternative impl would be to save the indices of the min and max elements. I'm not saying you need to make that change, just offering it as an option.

2024-03-12 14:11 UTC, brooksprumo commented on accounts-db/src/tiered_storage/meta.rs
> +            max_address: &DEFAULT_ACCOUNT_ADDRESS,
The default min should start as the maximum value (`Pubkey::from([0xFF; 32])`), and the default max should start as the minimum value (`Pubkey::from([0x00; 32])`). Please do not rely on `default()` when you need explicit values.

2024-03-12 14:11 UTC, brooksprumo commented on accounts-db/src/tiered_storage/meta.rs
> +        }
The default pubkey is a valid address, so I don't think we want to skip it. So I think we can simplify to:

```rust
if *address < *self.min {
    self.min = address;
}
if *address > *self.max {
    self.max = address;
}
```

2024-03-12 14:11 UTC, brooksprumo commented on accounts-db/src/tiered_storage.rs
> +                verify_test_account_with_footer(
I see this checks the address are within the footer's range. Do you think we should also have a test that checks for the specific min and max values too?

2024-03-13 02:01 UTC, yhchiang-sol commented on accounts-db/src/tiered_storage/meta.rs
> +        }
My original thought is that if the default key is common in most AccountsFile, then assuming the default key appears in most files and skipping the default key in the range might give us a more accurate range, but I think my original thought might complicate the design, esp. after shrinking.  So let's not treat the default key anything special.

2024-03-13 02:02 UTC, yhchiang-sol commented on accounts-db/src/tiered_storage.rs
> +                verify_test_account_with_footer(
Definitely.  Especially after we change the default to `[0, 0xffff..]`.  Will improve the test.

2024-03-13 13:16 UTC, brooksprumo commented on accounts-db/src/tiered_storage/meta.rs
> +        }
The default pubkey is common as an *owner* but I don't think it'll show up as an account address, since it's the system program.

2024-03-13 13:36 UTC, brooksprumo commented on accounts-db/src/tiered_storage/meta.rs
> +        let address = Pubkey::new_from_array(address_array);
This can be simplified with [solana_sdk::pubkey::new_rand()](https://docs.rs/solana-sdk/latest/solana_sdk/pubkey/fn.new_rand.html) to:

```suggestion
        let address = solana_sdk::pubkey::new_rand();
```

2024-03-13 13:36 UTC, brooksprumo commented on accounts-db/src/tiered_storage/meta.rs
> +            let address = Pubkey::new_from_array(address_array);
Same thing here.

2024-03-13 13:36 UTC, brooksprumo commented on accounts-db/src/tiered_storage/meta.rs
> +        assert!(*address_range.max <= address);
I'm not really sure what this is intending to check. Does the specific value from `default()` really matter before calling `update()`? The implicit API contract says to me that the min/max values are garbage until `update()` has been called at least once.

2024-03-13 13:36 UTC, brooksprumo commented on accounts-db/src/tiered_storage/test_utils.rs
> +    }
Why is this still special-casing a default address?

2024-03-13 17:23 UTC, yhchiang-sol commented on accounts-db/src/tiered_storage/test_utils.rs
> +    }
My bad.  Missed the test_utils.rs.  Will fix it.

2024-03-13 17:24 UTC, yhchiang-sol commented on accounts-db/src/tiered_storage/meta.rs
> +        assert!(*address_range.max <= address);
I think they're unnecessary.  Will fix it.

2024-03-20 05:41 UTC, yhchiang-sol commented on accounts-db/src/tiered_storage/test_utils.rs
> +    }
Removed special default case.

2024-03-20 05:42 UTC, yhchiang-sol commented on accounts-db/src/tiered_storage/meta.rs
> +        assert!(*address_range.max <= address);
Removed

2024-03-20 05:42 UTC, yhchiang-sol commented on accounts-db/src/tiered_storage/meta.rs
> +        let address = Pubkey::new_from_array(address_array);
Changed to Pubkey::new_unique().  new_rand() has been deprecated.

2024-03-20 05:42 UTC, yhchiang-sol commented on accounts-db/src/tiered_storage/meta.rs
> +            let address = Pubkey::new_from_array(address_array);
Changed to Pubkey::new_unique().  new_rand() has been deprecated.

2024-03-20 05:58 UTC, yhchiang-sol commented on accounts-db/src/tiered_storage.rs
> +                verify_test_account_with_footer(
Added new unit-tests under meta.rs, and also verify the min and max range from the footer in the test under tiered_storage.rs.

2024-03-20 14:39 UTC, brooksprumo commented on accounts-db/src/tiered_storage/meta.rs
> +        let address = Pubkey::new_from_array(address_array);
> Changed to Pubkey::new_unique(). new_rand() has been deprecated.

`Pubkey::new_rand()` is deprecated, but not `solana_sdk::pubkey::new_rand()`, which is the one I suggested. If you use `Pubkey::new_unique()`, you may always get the same value for the pubkey from run to run, since it is not intending to be random.

Also, for the tests, the pubkeys will always be in a sorted order. So that's not a good test scenario.

2024-03-20 14:51 UTC, brooksprumo commented on accounts-db/src/tiered_storage/meta.rs
> +}
Does this need to be a lazy static?

2024-03-20 14:55 UTC, brooksprumo requested changes

2024-03-20 14:55 UTC, brooksprumo commented on accounts-db/src/tiered_storage/meta.rs
> +            let address = Pubkey::new_unique();
Please use `solana_sdk::pubkey::new_rand()` instead.

See https://github.com/anza-xyz/agave/pull/172#discussion_r1532206135 for more discussion.

2024-03-20 16:49 UTC, yhchiang-sol commented on accounts-db/src/tiered_storage/meta.rs
> +        let address = Pubkey::new_from_array(address_array);
Aghh, got it.

2024-03-20 16:51 UTC, yhchiang-sol commented on accounts-db/src/tiered_storage/meta.rs
> +}
Done.  Made them const.

2024-03-20 16:51 UTC, yhchiang-sol commented on accounts-db/src/tiered_storage/meta.rs
> +            let address = Pubkey::new_unique();
Fixed

2024-03-20 17:11 UTC, brooksprumo commented on accounts-db/src/tiered_storage/meta.rs
> +        assert!(*address_range.max == address);
Wdyt about `assert_eq!` here?

2024-03-20 17:13 UTC, yhchiang-sol commented on accounts-db/src/tiered_storage/meta.rs
> +        assert!(*address_range.max == address);
Done!

2024-03-20 17:18 UTC, brooksprumo approved these changes
:shipit:

2024-03-20 19:17 UTC, merged