[ed25519] Use `verify_strict` for signature verification in ed25519 precompile
anza-xyz/agave pull request #1876
Opened 2024-06-26 03:05 UTC by samkim-crypto

#### Problem

#### Summary of Changes

Fixes #

2024-06-26 09:15 UTC, seanyoung reviewed
Looks good, but I think it needs a test case.

2024-06-26 16:50 UTC, 0x0ece commented
Example test:
https://github.com/0x0ece/agave/commit/ba98faacb61ce19862ee2edfe277fdaf9c10432d

2024-06-27 08:51 UTC, seanyoung approved these changes, later dismissed
Looks great

2024-06-27 21:09 UTC, t-nelson commented
code looks good. we should probably remeasure runtime to be sure the CU price doesn't need adjusted

2024-06-29 02:48 UTC, samkim-crypto commented
I ran the [benches](https://github.com/anza-xyz/agave/blob/master/sdk/benches/ed25519_instructions.rs) on my devserver and it does seem that `verify_strict` increases cost by ~4-5%.

Standard verification
```
test bench_ed25519_len_032 ... bench:      53,174.08 ns/iter (+/- 320.90)
test bench_ed25519_len_128 ... bench:      53,227.03 ns/iter (+/- 460.80)
test bench_ed25519_len_32k ... bench:     105,673.43 ns/iter (+/- 215.66)
test bench_ed25519_len_max ... bench:     157,801.53 ns/iter (+/- 393.42)
```

Strict verification
```
test bench_ed25519_len_032 ... bench:      56,098.69 ns/iter (+/- 652.68)
test bench_ed25519_len_128 ... bench:      56,373.39 ns/iter (+/- 408.99)
test bench_ed25519_len_32k ... bench:     109,504.36 ns/iter (+/- 2,027.92)
test bench_ed25519_len_max ... bench:     163,012.00 ns/iter (+/- 644.40)
```

2024-06-29 16:14 UTC, 0x0ece commented
The bench is expected, however all precompiles cost like a tx sigverify, and sigverify is already using verify_strict.

If anything, users were charged 4-5% extra before, after this change they’ll be charged “correctly” (And are prob undercharged when using secp256k1, but this is off topic here)

2024-07-02 12:34 UTC, seanyoung submitted a review, later dismissed

2024-07-03 01:19 UTC, samkim-crypto commented
Hm, it does seem like the CU price for sigverify and precompile ed25519 are assigned different values in the cost model. @tao-stones, can you help if the current cost model for ed25519 is adequate? Looking at the commit history of the cost model, I can't seem to find how the cost models were originally assigned.

2024-07-03 03:06 UTC, 0x0ece commented
Do you have ref to the code? TBH I was quoting something I saw in [firedancer](https://github.com/firedancer-io/firedancer/blob/main/src/flamenco/runtime/fd_runtime.c#L2654), so maybe we have implemented the wrong thing...

2024-07-03 03:54 UTC, tao-stones commented
> Hm, it does seem like the CU price for sigverify and precompile ed25519 are assigned different values in the cost model. @tao-stones, can you help if the current cost model for ed25519 is adequate? Looking at the commit history of the cost model, I can't seem to find how the cost models were originally assigned.

Hey @samkim-crypto, precompiled costs were determined by benching (under `sdk/benches`). Transaction sigverify process is optimized, so it'd have different performance than ed25519 or secp256k1, iirc.

2024-07-03 05:09 UTC, samkim-crypto commented
> Do you have ref to the code? TBH I was quoting something I saw in [firedancer](https://github.com/firedancer-io/firedancer/blob/main/src/flamenco/runtime/fd_runtime.c#L2654), so maybe we have implemented the wrong thing...

@0x0ece, I believe the costs for the precompiles are defined in the `solana-cost-model` crate [(here](https://github.com/anza-xyz/agave/blob/master/cost-model/src/block_cost_limits.rs#L30))

> > Hm, it does seem like the CU price for sigverify and precompile ed25519 are assigned different values in the cost model. @tao-stones, can you help if the current cost model for ed25519 is adequate? Looking at the commit history of the cost model, I can't seem to find how the cost models were originally assigned.
> 
> Hey @samkim-crypto, precompiled costs were determined by benching (under `sdk/benches`). Transaction sigverify process is optimized, so it'd have different performance than ed25519 or secp256k1, iirc.

@tao-stones, if I run the [benches](https://github.com/anza-xyz/agave/blob/master/sdk/benches/ed25519_instructions.rs), I consistency get about 4-5% increase in the timing both in my local and dev machines. Do you think it is reasonable to increase the constant factor [here](https://github.com/anza-xyz/agave/blob/master/cost-model/src/block_cost_limits.rs#L30) by 5%?

2024-07-03 14:43 UTC, tao-stones commented
> if I run the [benches](https://github.com/anza-xyz/agave/blob/master/sdk/benches/ed25519_instructions.rs), I consistency get about 4-5% increase in the timing both in my local and dev machines. Do you think it is reasonable to increase the constant factor [here](https://github.com/anza-xyz/agave/blob/master/cost-model/src/block_cost_limits.rs#L30) by 5%?

the message length matters, currently tx can have 1K at most. iirc, it was benched with 3k message len to be reasonably conservative. Assuming 5% increase you are seeing are with different message len?

2024-07-04 00:53 UTC, samkim-crypto commented
Yeah I did some more formal testing and I seem to be getting about 4% max increase on any message lengths on my dev machine. It does seem reasonable to increase the cost [constant](https://github.com/anza-xyz/agave/blob/master/cost-model/src/block_cost_limits.rs#L30) by 4%, so either 79 (maybe 80).

Standard verification
```
test bench_ed25519_len_032 ... bench:      53,239.98 ns/iter (+/- 498.79)
test bench_ed25519_len_128 ... bench:      53,477.30 ns/iter (+/- 370.17)
test bench_ed25519_len_1k  ... bench:      54,969.69 ns/iter (+/- 329.04)
test bench_ed25519_len_3k  ... bench:      58,245.12 ns/iter (+/- 245.52) <-- 3k
test bench_ed25519_len_5k  ... bench:      61,531.41 ns/iter (+/- 260.65)
test bench_ed25519_len_8k  ... bench:      66,428.60 ns/iter (+/- 229.59)
test bench_ed25519_len_16k ... bench:      79,600.47 ns/iter (+/- 335.06)
test bench_ed25519_len_32k ... bench:     105,824.82 ns/iter (+/- 339.31)
test bench_ed25519_len_max ... bench:     157,929.05 ns/iter (+/- 576.27)
```

Strict verification
```
test bench_ed25519_len_032 ... bench:      54,971.81 ns/iter (+/- 972.73) <-- 3.25% increase
test bench_ed25519_len_128 ... bench:      55,226.82 ns/iter (+/- 730.51) <-- 3,27% increase
test bench_ed25519_len_1k  ... bench:      56,739.93 ns/iter (+/- 1,401.09) <-- 3.22% increase
test bench_ed25519_len_3k  ... bench:      59,967.48 ns/iter (+/- 284.36) <-- 2.95% increase
test bench_ed25519_len_5k  ... bench:      63,248.71 ns/iter (+/- 211.82) <-- 3.79% increase
test bench_ed25519_len_8k  ... bench:      68,155.69 ns/iter (+/- 330.51) <-- 2.60% increase
test bench_ed25519_len_16k ... bench:      81,229.28 ns/iter (+/- 283.99) <-- 2.05% increase
test bench_ed25519_len_32k ... bench:     107,439.18 ns/iter (+/- 405.38) <-- 1.53% increase
test bench_ed25519_len_max ... bench:     159,484.30 ns/iter (+/- 344.30) <-- 0.98% increase
```

2024-07-09 00:06 UTC, tao-stones requested changes

2024-07-09 00:06 UTC, tao-stones commented on cost-model/src/block_cost_limits.rs
> +pub const ED25519_VERIFY_COST: u64 = COMPUTE_UNIT_TO_US_RATIO * 80;
No objection on changing default. It probably should be back ported to 2.0, or put this change behind a feature gate.

2024-07-09 00:28 UTC, samkim-crypto commented on cost-model/src/block_cost_limits.rs
> +pub const ED25519_VERIFY_COST: u64 = COMPUTE_UNIT_TO_US_RATIO * 80;
Makes sense! I put the changes under the feature gate.

2024-07-09 00:34 UTC, tao-stones approved these changes

2024-07-10 00:19 UTC, merged