bench-tps: allow option to not set account data size on every transaction
anza-xyz/agave pull request #209
Opened 2024-03-12 15:02 UTC by anwayde

#### Problem

Bench TPS needs [this feature](https://github.com/solana-labs/solana/issues/30366) activated on the cluster since all transactions are hardcoded to include the instruction to set the account data size. However, this will not work on a test cluster where this feature is not activated. Moreover, Firedancer currently does not support that instruction.

#### Summary of Changes

This adds a flag `--skip-tx-account-data-size` which when specified, will not add that instruction. This makes Bench TPS work with FIredancer (and Solana clusters without any features activated).

Fixes #

2024-03-12 16:50 UTC, KirillLykov requested changes
looks good except for one small change

2024-03-12 16:50 UTC, KirillLykov commented on bench-tps/src/bench.rs
> +        let data_size_limit = match skip_tx_account_data_size {
I think match is not needed here, can be done with `if` statement.

2024-03-12 23:02 UTC, gregcusack requested changes

2024-03-12 23:02 UTC, gregcusack commented on bench-tps/src/bench.rs
> +            true => 0,
using `data_size_limit <- 0` to indicate there is no limit is a little confusing. maybe I'd use an `Option<u32>`. That way if it is `Some()` then there is a limit and if it is `None` there is no limit

2024-03-13 10:09 UTC, KirillLykov commented on bench-tps/src/bench.rs
> +        let data_size_limit = match skip_tx_account_data_size {
In the light of the Greg's comment, maybe something like:
 
```rust
let data_size_limit = (!skip_tx_account_data_size)
            .then(|| get_transaction_loaded_accounts_data_size(enable_padding));
```

2024-03-13 10:12 UTC, KirillLykov commented on bench-tps/src/send_batch.rs
> +            if data_size_limit != 0 {
If `data_size_limit` becomes `Option<u32>`:
```suggestion
            if let Some(data_size_limit) = data_size_limit
```

2024-03-13 16:32 UTC, KirillLykov approved these changes

2024-03-13 16:46 UTC, gregcusack approved these changes
lgtm!

2024-03-13 19:29 UTC, merged