fix docs format
anza-xyz/agave pull request #2492
Opened 2024-08-08 13:51 UTC by yihau

(part of #2487)

#### Problem

![Screenshot 2024-08-08 at 21 49 51](https://github.com/user-attachments/assets/287f4eb5-d00d-4445-a4ff-c4e1122362fa)

docs take a stricter approach to indentation rules…

#### Summary of Changes

fix it

2024-08-08 16:44 UTC, brooksprumo requested changes

2024-08-08 16:44 UTC, brooksprumo commented on accounts-db/src/account_storage.rs
> +    ///
Looks like these do not belong as part of (2), so maybe the fix is to add a new line instead?
```suggestion
    ///
    ///    Operations like shrinking or write cache flushing may have updated the index between when the caller read the index and called this function to
    ///    load from the append vec specified in the index.
    ///
```

2024-08-08 16:44 UTC, brooksprumo commented on accounts-db/src/ancient_append_vecs.rs
> +//!    Otherwise, an ancient append vec is the same as any other append vec
I think this is not part of 2.

```suggestion
//!
//!    Otherwise, an ancient append vec is the same as any other append vec
```

2024-08-09 07:11 UTC, yihau commented on accounts-db/src/account_storage.rs
> +    ///
sure!

2024-08-09 07:12 UTC, yihau commented
thank you! just committed those 2 changes 🫡

2024-08-09 11:30 UTC, brooksprumo requested changes

2024-08-09 11:30 UTC, brooksprumo commented on accounts-db/src/account_storage.rs
> +    ///    load from the append vec specified in the index.
I think the extra leading spaces can be removed.

2024-08-09 11:30 UTC, brooksprumo commented on accounts-db/src/ancient_append_vecs.rs
> +//!    Otherwise, an ancient append vec is the same as any other append vec
Same here.

2024-08-09 17:32 UTC, yihau commented on accounts-db/src/account_storage.rs
> +    ///    load from the append vec specified in the index.
thank you for catching this one! fixed: [1b6f399](https://github.com/anza-xyz/agave/pull/2492/commits/1b6f3992e9913e7a013445ecb4b00193dd898d47)

2024-08-09 17:34 UTC, yihau commented on accounts-db/src/ancient_append_vecs.rs
> +//!    Otherwise, an ancient append vec is the same as any other append vec
same here! [828cad4](https://github.com/anza-xyz/agave/pull/2492/commits/828cad45b93368b88c9fd4760bd59cec66d099c6) thank you very much! I almost commit a weird docs format into master 🙈

2024-08-09 17:38 UTC, brooksprumo approved these changes
:shipit:

2024-08-11 09:14 UTC, merged