Add a `--no-header` flag for CLI rent calculation
anza-xyz/agave pull request #2663
Opened 2024-08-19 19:51 UTC by blockiosaurus

#### Problem
It's currently inconvenient attempting to calculate rent changes in accounts (e.g. rent cost of adding 8 bytes of padding). The CLI provides the ability to easily find the rent for a Solana account using `solana rent 8` but it doesn't provide the ability to ignore the 128-byte account header, requiring the extra steps of subtracting `solana rent 0` from the rent calculation.

#### Summary of Changes
This PR adds a --no-header flag to subtract the 128-byte header rent from the calculation. The flag is optional and defaults to false to maintain backwards compatibility.

2024-08-20 02:22 UTC, buffalojoec submitted a review, later dismissed
Nice, makes sense to me. Thanks!

2024-08-20 02:28 UTC, CriesofCarrots requested changes

2024-08-20 02:28 UTC, CriesofCarrots commented on cli/src/cluster_query.rs
> +                        .help("Exclude rent header from calculation"),
Is "rent header" a term being popularized anywhere? I don't think most users would know what this means.
In the solana-program `rent` module, we call this "account storage overhead".

2024-08-20 02:28 UTC, CriesofCarrots commented on cli/src/cluster_query.rs
> +        rent.minimum_balance(data_length) - rent.minimum_balance(0)
```suggestion
        ((data_length as u64 * rent.lamports_per_byte_year) as f64 * rent.exemption_threshold) as u64
```
I'd prefer to do the actual calculation only once

2024-08-20 02:37 UTC, CriesofCarrots commented
@blockiosaurus , sorry for the review whiplash! I didn't see Joe's when I posted.
However, I still think we can improve this a bit and would love your response to my comments.

2024-08-23 13:17 UTC, blockiosaurus commented on cli/src/cluster_query.rs
> +                        .help("Exclude rent header from calculation"),
This is what we [use in Umi](https://umi.typedoc.metaplex.com/types/umi.RpcGetRentOptions.html), and "header" is shorter 😄 but I have no strong opinions on naming.

2024-08-23 13:21 UTC, blockiosaurus commented
Awesome, thank you! I've added your changes and am open to whatever naming is clearest for the flag name.

2026-01-12 22:43 UTC, steviez commented on cli/src/cluster_query.rs
> +                        .help("Exclude rent header from calculation"),
This PR is very old so not sure if there is any interest in picking it back up. However, I agree with `CriesofCarrots` on naming; I feel like "rent header" doesn't accurately capture what it is. To me, "rent header" sounds like some section of data that pertains to rent. But really, we're talking about the "account storage overhead" which you have to pay rent for as well**

I think "account storage overhead" is kind of verbose; another option could be renaming the flag to be something like `--calculate-difference` to interpret the (signed) value as a change in account size and report the change in rent.

** As a quick reminder, remember that rent collection as a concept is dead and accounts must maintain a balance of at least the rent exemption minimum (which is dependent on account size)

2026-01-13 00:11 UTC, blockiosaurus commented on cli/src/cluster_query.rs
> +                        .help("Exclude rent header from calculation"),
We could always do solana rent --no-overhead

2026-04-03 08:26 UTC, closed without merging