panic when exceed in-mem index budget
anza-xyz/agave pull request #2721
Opened 2024-08-23 16:31 UTC by HaoranYi

#### Problem

#### Summary of Changes

Fixes #

2024-08-23 18:49 UTC, jeffwashington requested changes
I don't think we should panic. I think we should oom if we're going to. Maybe the system recovers. For example, on pop, just let it use whatever memory it needs during some peak time.  I think we get rid of the limit completely. It is also a cli arg which needs to be removed from lt and validator.

2024-08-23 19:20 UTC, HaoranYi commented
> I don't think we should panic. I think we should oom if we're going to. Maybe the system recovers. For example, on pop, just let it use whatever memory it needs during some peak time. I think we get rid of the limit completely. It is also a cli arg which needs to be removed from lt and validator.

Sure. will change. 
A related question: do we still want to keep the cli arg for `disable_accounts_disk_index`?

2024-08-23 19:25 UTC, jeffwashington commented
> A related question: do we still want to keep the cli arg for `disable_accounts_disk_index`?

yes, for the moment.

2024-08-23 21:07 UTC, jeffwashington submitted a review, later dismissed
lgtm

2024-08-24 13:13 UTC, brooksprumo requested changes

2024-08-24 13:13 UTC, brooksprumo commented on validator/src/cli.rs
> -        )
We cannot just remove a public arg. It needs to be deprecated instead. We have to wait until v3.0 to remove the arg.

2024-08-24 15:24 UTC, HaoranYi commented on validator/src/cli.rs
> -        )
Ah. Yes. Updated.

2024-08-27 12:46 UTC, brooksprumo commented on accounts-db/src/accounts_index/in_mem_accounts_index.rs
> +
nit: Can this newline be removed?
```suggestion
```

2024-08-27 12:46 UTC, brooksprumo commented on accounts-db/src/accounts_index/in_mem_accounts_index.rs
> -            }),
Now that we don't have a size limit, does that mean our tests no longer actually exercise the disk index?

2024-08-27 12:46 UTC, brooksprumo commented on accounts-db/src/bucket_map_holder.rs
> +            .unwrap_or(&IndexLimitMb::Unlimited)
Can this be `unwrap_or_default()`? Then we don't have multiple places where we set a default.
```suggestion
            .unwrap_or_default()
```

2024-08-27 12:46 UTC, brooksprumo commented on accounts-db/src/bucket_map_holder.rs
> +            index_limit_mb: IndexLimitMb::Unlimited,
Should we remove this `index_limit_mb` entirely and use the default directly?

```rust
let config = AccountsIndexConfig::default();
```

If the defaults change such that the disk index is disabled, then this test will fail (iiuc), so I think the test is still correct.

2024-08-27 12:46 UTC, brooksprumo commented on ledger-tool/src/args.rs
> -            .conflicts_with("accounts_index_memory_limit_mb"),
Since we are deprecating `--accounts-index-memory-limit-mb`, not removing it, I think we should keep this `conflicts_with` line.

2024-08-27 12:46 UTC, brooksprumo commented on validator/src/cli.rs
> +    add_arg!(Arg::with_name("accounts_index_memory_limit_mb")
When I removed args in 2.0, it was not easy to find which versions things were deprecated in (this was needed for reviewers to know if it was safe to remove or not). I think we can help our future selves out by adding a comment here. Something like:

```suggestion
    // deprecated in v2.1 by PR #2721
    add_arg!(Arg::with_name("accounts_index_memory_limit_mb")
```

2024-08-27 12:46 UTC, brooksprumo commented on validator/src/cli.rs
> -        .conflicts_with("accounts_index_memory_limit_mb"));
Here too, I think we should keep the `conflicts_with` line.

2024-08-27 16:18 UTC, HaoranYi commented on ledger-tool/src/args.rs
> -            .conflicts_with("accounts_index_memory_limit_mb"),
For ledger-tool, we can remove `accounts_index_memory_limit_mb` directly, no need to deprecate. So I think we remove `conflicts_with` here.

2024-08-27 16:18 UTC, HaoranYi commented on accounts-db/src/bucket_map_holder.rs
> +            .unwrap_or(&IndexLimitMb::Unlimited)
done.
looks like `unwrap_or_default()` don't work with ref. 
so use `unwrap_or` with explicit IndexLimitMb::Default().

2024-08-27 16:18 UTC, HaoranYi commented on accounts-db/src/accounts_index/in_mem_accounts_index.rs
> +
done.

2024-08-27 16:18 UTC, HaoranYi commented on validator/src/cli.rs
> +    add_arg!(Arg::with_name("accounts_index_memory_limit_mb")
done!

2024-08-27 16:18 UTC, HaoranYi commented on validator/src/cli.rs
> -        .conflicts_with("accounts_index_memory_limit_mb"));
done.

2024-08-27 16:18 UTC, HaoranYi commented on accounts-db/src/bucket_map_holder.rs
> +            index_limit_mb: IndexLimitMb::Unlimited,
done.

2024-08-27 16:18 UTC, HaoranYi commented on accounts-db/src/accounts_index/in_mem_accounts_index.rs
> -            }),
Good question. 

no. 

This helper fn is used in `test_hold_range_in_memory`, in which we test `hold_range_in_memory` api, which explicilty call `stop_eviction()`. The limit arg has no impact for this test.

We are still exercising the same test function as before.

2024-08-27 17:47 UTC, brooksprumo commented on accounts-db/src/bucket_map_holder.rs
> +            .unwrap_or(&IndexLimitMb::Unlimited)
Or have the `.map()` not return a reference. Since the enum is effectively just an integer, copying is fast.

(This is impl is fine though. No need to change.)

2024-08-27 17:49 UTC, brooksprumo commented on ledger-tool/src/args.rs
> -            .conflicts_with("accounts_index_memory_limit_mb"),
Oh, ok that makes sense.

2024-08-27 17:51 UTC, brooksprumo submitted a review, later dismissed
:shipit:

2024-08-27 19:33 UTC, HaoranYi commented on accounts-db/src/bucket_map_holder.rs
> +            .unwrap_or(&IndexLimitMb::Unlimited)
done!

2024-08-27 19:41 UTC, brooksprumo approved these changes

2024-08-28 13:26 UTC, merged