add tx_priority_fee argument for program deploy subcommand
anza-xyz/agave pull request #312
Opened 2024-03-19 04:40 UTC by Nagaprasadvr

Issue - https://github.com/anza-xyz/agave/issues/21

Add Transaction priority fee argument in terms of LAMPORTS to solana program deploy subcommand

Problem
solana program deploy command could take a lot of time to finish due to program code size .Transaction execution speeds can be increased or txs can be prioritised by setting compute_unit_price (priority fee) for every tx this price is set and txs are executes faster than normal therefore making program deployment faster.
usage - solana program deploy --tx-priority-fee 1000000
Summary of Changes
solana/cli/program - added tx_priority_fee logic

2024-03-19 04:43 UTC, Nagaprasadvr commented
apologies for creating a new pr 
#144 was closed because i had forked solana-labs repo not agave so had to create this pr again!

2024-03-19 05:01 UTC, Nagaprasadvr commented
found a workaround for  setting compute units based on programs
@jstarry

i have added 2000 cu when program is neither system_program or bpf_upgradable_loader

![image](https://github.com/anza-xyz/agave/assets/81755170/9c104c96-278f-4118-8bd0-341906a9c4e3)

2024-03-21 13:22 UTC, jstarry requested changes
None of the `set_compute_budget_ixs_if_needed` call-sites pass the actual message instructions into the function so the `compute_unit_limit` isn't being set properly.

2024-03-21 13:22 UTC, jstarry commented on cli/src/program.rs
> +    initial_instructions.extend(ixs);
Compute budget instructions should only be added if `!ixs.is_empty()`

2024-03-21 13:22 UTC, jstarry commented on cli/src/program.rs
> +        initial_instructions.extend(ixs);
Same here, need to check if `!ixs.is_empty()` first

2024-03-21 13:22 UTC, jstarry commented on cli/src/program.rs
> +        ));
compute budget instructions need to be inserted at the beginning of the instruction list

2024-03-21 13:22 UTC, jstarry commented on transaction-dos/src/main.rs
> +            compute_unit_price,
```suggestion
            compute_unit_price: None,
```

2024-03-21 13:22 UTC, jstarry commented on cli/tests/program.rs
> +    config.json_rpc_url = "https://api.devnet.solana.com".to_string();
We should not be using devnet for tests...

2024-03-21 13:23 UTC, jstarry commented
@Nagaprasadvr thanks for getting this started but I'm going to take this over since the tests need a lot of work and I want this PR merged relatively quickly if possible.

2024-03-21 13:29 UTC, Nagaprasadvr commented
> @Nagaprasadvr thanks for getting this started but I'm going to take this over since the tests need a lot of work and I want this PR merged relatively quickly if possible.

sure im happy with that ! program deployments have been failing recently for big programs hope this fix will help that !

2024-03-21 16:21 UTC, jstarry commented
Moved to https://github.com/anza-xyz/agave/pull/364

2024-03-21 16:21 UTC, closed without merging