Updated validator docs
anza-xyz/agave pull request #3134
Opened 2024-10-10 18:38 UTC by tvanemmerik

#### Problem

Updated validator docs

#### Summary of Changes

- Added a section about validator calls
- Fixed some typos
- Added and updated networking/firewall related content
- Changed formatting

2024-11-12 15:00 UTC, tigarcia requested changes
Looks good overall. Since you're already in the best-practices file, could you update the example agave-install example to be more recent?  It should be agave-install 2.0.15.  Thanks for contributing to the docs!

2024-11-12 15:00 UTC, tigarcia commented on docs/src/operations/best-practices/security.md
> +The default setup should work out-of-the-box by simply installing `fail2ban`:
Thanks for fixing my typos!

2024-11-14 18:27 UTC, tvanemmerik reviewed
Changed the agave-install init command to 2.0.15

2024-11-14 18:27 UTC, tvanemmerik commented on docs/src/operations/best-practices/security.md
> +The default setup should work out-of-the-box by simply installing `fail2ban`:
You're welcome 😃

2025-02-12 21:31 UTC, tigarcia approved these changes

2025-02-13 11:43 UTC, yihau approved these changes
fixed the group permissions and added the approval status for @tigarcia

2025-02-13 11:44 UTC, yihau commented
all docs changes. ignore CI

2025-02-13 11:44 UTC, merged