Rekey - alt_bn128 and poseidon_syscall
anza-xyz/agave pull request #319
Opened 2024-03-19 18:01 UTC by Lichtso

#### Problem
#294 requires new feature gate keys.

#### Summary of Changes
- Rekeys `enable_alt_bn128_compression_syscall` and `enable_poseidon_syscall`.
- Adds `simplify_alt_bn128_syscall_error_codes`.

2024-03-19 18:02 UTC, 0x0ece approved these changes

2024-03-20 00:37 UTC, 0x0ece requested changes
We rediscussed this. No rekey, just 1 new feature gate.

2024-03-21 14:15 UTC, 0x0ece approved these changes

2024-03-22 02:56 UTC, samkim-crypto approved these changes

2024-03-22 06:58 UTC, merged