feat(pubsub): Implement Ping/Pong Mechanism to Improve Connection Reliability
anza-xyz/agave pull request #3845
Opened 2024-11-30 07:39 UTC by 0xIchigo

#### Problem
Both the blocking and nonblocking `PubsubClient` clients currently lack a mechanism to detect when the WebSocket connection becomes unresponsive or stale. Without periodic health checks, the clients may not realize that the server is no longer responding. This can lead to missed messages and unreliable subscriptions. This can affect applications relying on WebSockets to provide real-time data streams

#### Summary of Changes
This PR aims to implement a ping/pong mechanism in both the blocking and nonblocking `PubsubClient` clients to improve connection reliability

**Changes**
- Introduced a periodic `Ping` message sent to the server using `tokio::time::interval`
- Added handling for incoming `Pong` messages and reset the `unmatched_pings` counter upon receiving any message
- Configured the client to close the connection gracefully if the `unmatched_pings` counter exceeds `DEFAULT_MAX_FAILED_PINGS`
- Ensured the changes did not significantly alter the existing code structure. This meant hardcoding `DEFAULT_PING_DURATION_SECONDS` and `DEFAULT_MAX_FAILED_PINGS`, as making them configurable would've meant changing the existing subscription parameters resulting in a breaking change. However, these params could easily be changed in the future to become configurable—the importance here is introducing reliable health checks to WebSocket connections

2025-01-07 20:21 UTC, CriesofCarrots reviewed
Thanks @0xIchigo, this seems pretty close. I have a couple small comments, and we'll have to see how CI fares.
While you're making updates, can you please rebase on master to remove all the merge commits and force-push?

2025-01-07 20:21 UTC, CriesofCarrots commented on pubsub-client/src/pubsub_client.rs
> +
While I suppose the blocking and nonblocking clients might need different configurations at some point in the future, let's import these rather than duplicating for now.

2025-01-07 20:21 UTC, CriesofCarrots commented on pubsub-client/src/nonblocking/pubsub_client.rs
> +        let mut unmatched_pings: usize = 0usize;
Can we come up with a better name for this variable? The code below isn't really monitoring how many specific pings are unmatched, just whether there's some kind of response in `DEFAULT_PING_DURATION_SECONDS * DEFAULT_MAX_FAILED_PINGS` seconds.

Maybe `elapsed_pings` or something like that?

2025-01-07 20:21 UTC, CriesofCarrots commented on pubsub-client/src/pubsub_client.rs
>              }
It is not clear to me why this error needs special handling. What am I missing?

2025-01-08 20:36 UTC, 0xIchigo commented on pubsub-client/src/pubsub_client.rs
>              }
Ah, that's my bad—I was going to treat the read time-out error separately but didn't see a real need for it and accidentally left it in. This part is redundant since we're treading timeout errors the same as any other error thrown. I'll remove it 🫡

2025-01-08 22:04 UTC, CriesofCarrots reviewed
I'm not going to run CI on this yet, as I can see it will not compile. Please fix compilation errors, thanks.

2025-01-08 22:04 UTC, CriesofCarrots commented on pubsub-client/src/nonblocking/pubsub_client.rs
> +use crate::nonblocking::pubsub_client::{DEFAULT_MAX_FAILED_PINGS, DEFAULT_PING_DURATION_SECONDS};
Does this compile? I don't think this is where these consts are defined.
Also, please keep imports to one `use` statement when possible.

2025-01-08 22:04 UTC, CriesofCarrots commented on pubsub-client/src/pubsub_client.rs
> +        let unmatched_pings: Arc<AtomicUsize> = Arc::new(AtomicUsize::new(0));
Same comment about ping matching from my original review.

2025-01-08 22:04 UTC, CriesofCarrots commented on pubsub-client/src/pubsub_client.rs
> +
My intent was that you leave the definitions in `nonblocking` add the import statement to this file.

2025-01-09 17:05 UTC, 0xIchigo commented on pubsub-client/src/nonblocking/pubsub_client.rs
> +use crate::nonblocking::pubsub_client::{DEFAULT_MAX_FAILED_PINGS, DEFAULT_PING_DURATION_SECONDS};
My apologies—I'm having issues building locally, so this is all off the cuff. Will change the import 🫡

2025-01-09 17:45 UTC, CriesofCarrots commented
Code does not compile; see CI.
Please run `cargo build` (and `fmt` and `clippy`) locally before pinging for review.

2025-01-10 23:13 UTC, 0xIchigo commented
My apologies @CriesofCarrots, I was able to fix all my build issues and run the code locally. All the compile errors should be fixed now!

2025-01-13 21:38 UTC, 0xIchigo commented
Sorry @CriesofCarrots—I rebased the PR to ensure it was in sync with the repo but noticed that another workflow approval is required for the tests to run. Is there anything else that needs to be changed to merge this PR, or are all the health checks good?

2025-01-14 01:15 UTC, CriesofCarrots commented
> Sorry @CriesofCarrots—I rebased the PR to ensure it was in sync with the repo but noticed that another workflow approval is required for the tests to run. Is there anything else that needs to be changed to merge this PR, or are all the health checks good?

Yes @0xIchigo, `cargo clippy` is making this complaint:
```
error: you seem to be trying to use `match` for destructuring a single pattern. Consider using `if let`
   --> pubsub-client/src/pubsub_client.rs:843:13
    |
843 | /             match maybe_tls_stream {
844 | |                 MaybeTlsStream::Plain(tcp_stream) => {
845 | |                     if let Err(e) = tcp_stream.set_read_timeout(Some(Duration::from_millis(500))) {
846 | |                         info!("Failed to set read timeout on TcpStream: {:?}", e);
...   |
850 | |                 _ => {}
851 | |             }
    | |_____________^
    |
    = help: for further information visit https://rust-lang.github.io/rust-clippy/master/index.html#single_match
    = note: `-D clippy::single-match` implied by `-D warnings`
    = help: to override `-D warnings` add `#[allow(clippy::single_match)]`
help: try
    |
843 ~             if let MaybeTlsStream::Plain(tcp_stream) = maybe_tls_stream {
844 +                 if let Err(e) = tcp_stream.set_read_timeout(Some(Duration::from_millis(500))) {
845 +                     info!("Failed to set read timeout on TcpStream: {:?}", e);
846 +                 }
847 +             }
    |
error: could not compile `solana-pubsub-client` (lib) due to 1 previous error
warning: build failed, waiting for other jobs to finish...
error: could not compile `solana-pubsub-client` (lib test) due to 1 previous error
🚨 Error: The command exited with status 101
```

2025-01-16 03:48 UTC, CriesofCarrots commented
@0xIchigo , there seems to be an issue with this code as per our CI test suite. Subscription tests are hanging. Can you please take a look?

2025-07-23 19:10 UTC, peigongdsd commented
Hello, is this PR still being worked on?

2025-10-01 01:24 UTC, steveluscher commented
Rebased this puppy and running CI.

2025-10-09 00:03 UTC, steveluscher commented
Rebased and running CI again.

2025-10-09 23:57 UTC, steveluscher commented on pubsub-client/src/nonblocking/pubsub_client.rs
> +                tungstenite::Error::Io(ref err) => err.kind() == std::io::ErrorKind::WouldBlock,
@0xIchigo, did you find this was necessary? I'm reading up on `tungstenite` and it seems that

* the blocking API (`connect()`) blocks to completion, so you don't have to handle `WouldBlock` errors
* the non-blocking API (`connect_async()`) handles `WouldBlock` errors transparently if you stick to the `next()` and `send()` APIs.

2025-10-10 00:31 UTC, 0xIchigo commented on pubsub-client/src/nonblocking/pubsub_client.rs
> +                tungstenite::Error::Io(ref err) => err.kind() == std::io::ErrorKind::WouldBlock,
Yes—since we use `set_read_timeout()` on the blocking socket, we get back a `WouldBlock` when the timeout expires. This allows for the loop to periodically wake up, send pings, and detect whenever there's a dead connection without needing async

2025-10-14 18:47 UTC, steveluscher requested changes
I think the only practical way to do this to both the blocking and non-blocking APIs is to make the change to the non-blocking API and then _use_ the non-blocking API from the blocking API using `Runtime::block_on()`. Essentially delete all the blocking code and use the non-blocking code via a [single threaded runtime](https://discord.com/channels/428295358100013066/977244255212937306/1426635761062645800).

2025-10-14 18:47 UTC, steveluscher commented on pubsub-client/src/pubsub_client.rs
> +            }
So, setting a read timeout only works for plain sockets. This makes it essentially useless for any practical purpose – secure socket connections to (for instance) `wss://api.mainnet-beta.solana.com` will skip this code.

2026-04-13 08:52 UTC, closed without merging