Eliminate some obviously useless threading
anza-xyz/agave pull request #4219
Opened 2024-12-28 23:20 UTC by alexpyattaev

#### Problem
pub fn ed25519_verify_disabled(batches: &mut [PacketBatch]) in perf/src/sigverify.rs
does pretty much no work (sets a boolean flag for each Packet in PacketBatch) and yet it creates doubly nested parallel iterators to achieve this results. It further does this on rayon's global thread pool so it is impossible to do accounting on this activity.

#### Summary of Changes
Changed the function to set the flags in single thread. Unless there are several thousands of packets in those batches, this will be faster.

2024-12-30 01:52 UTC, steviez requested changes
Hi @alexpyattaev - The PR description and code changes don't match; the problem description refers to sigverify but the actual diff is touching rocksdb.

Ignoring that and responding to the rocksdb changes, I still think wiring things up to be configurable (on the CLI for now since that is where everything else is) is the right move for now to allow some customization & leave an escape hatch for later.

I have https://github.com/anza-xyz/agave/pull/4214 which does that; I opened this a couple days ago but didn't add reviewers and/or draw attention to it in light of the holidays. I think our efforts were mostly tangential here, but we can make sure to coordinate better in Slack to avoid any duplicated efforts moving forwards

2024-12-30 11:04 UTC, alexpyattaev commented
Sorry I have pushed the wrong diff. Should not make PRs late at night. Especially the "small and trivial" ones.

2025-01-02 15:55 UTC, KirillLykov approved these changes, later dismissed

2025-01-02 16:43 UTC, steviez commented
> Unless there are several thousands of packets in those batches, this will be faster.

I'm not sure if this function can actually get called in production, but if you look at `SigverifyStage`, 1000's of packets is not completely unexpected
https://github.com/anza-xyz/agave/blob/e3f99e6391bdd42a2420af0bbbfcf3961d084e7b/core/src/sigverify_stage.rs#L35-L36

2025-01-02 17:00 UTC, alexpyattaev commented
I guess the whole point was to save resources by skipping verify in some debug/devel runs. I guess if we are dealing with truly huge numbers of packets parallelizing it may still be wise. Changed to act same as the "real" version, which works without nested parallel iterators.

2025-01-03 05:09 UTC, steviez commented
> Changed to act same as the "real" version, which works without nested parallel iterators.

Yeah, this seems like a reasonable change; make it somewhat match the real one. Would you mind updating the problem description / summary of changes to more accurately reflect the new change ? I know this is a fairly minor change, but I think it is nice to have PR descriptions match the underlying code change incase we're bisecting or doing something else that involves looking through history

2025-01-03 19:53 UTC, steviez approved these changes
LGTM

2025-01-03 21:30 UTC, merged