cli: adding prio fee support to validator-info
anza-xyz/agave pull request #582
Opened 2024-04-04 20:19 UTC by kaplanmaxe

#### Problem

Adding priority fee support to `solana validator-info publish`

#### Summary of Changes

Adding priority fee support to `solana validator-info publish`

Fixes #

2024-04-15 21:43 UTC, joncinque requested changes
Thanks for your contribution! Can you run `./cargo nightly fmt --all` from the top of the repo to format? CI is failing due to the formatting issue right now

2024-04-16 12:22 UTC, kaplanmaxe commented
Sorry about that @joncinque . Fixed, rebased, and squashed

2024-04-16 21:22 UTC, joncinque reviewed
The change looks good, but I realized it won't built at this point because of a change I just merged. Could you rebase one last time? Then I'll merge once it passes CI.

If that's too annoying, I can also take care of it

2024-04-16 21:22 UTC, joncinque commented on cli/src/validator_info.rs
> +        compute_unit_price::WithComputeUnitPrice,
Crap, darn, I Just realized I broke this with #826, can you rebase and update this line?
```suggestion
        compute_budget::WithComputeUnitPrice,
```

2024-04-17 00:04 UTC, kaplanmaxe commented
No worries at all @joncinque . Just pushed. Thanks!

2024-04-17 10:36 UTC, joncinque approved these changes
Thanks again for doing the work!

2024-04-17 10:36 UTC, merged