multibind with ports tracking
anza-xyz/agave pull request #626
Opened 2024-04-06 14:26 UTC by HaoranYi

#### Problem

- keep track of ports and reused_port for sock binding

#### Summary of Changes

Fixes #

2024-04-06 15:33 UTC, t-nelson requested changes
i feel like this could be rewritten with less replicode, but it is exactly the kind of solution that net-utils deserves

2024-04-06 15:33 UTC, t-nelson commented on net-utils/src/lib.rs
> +        if !reused_ports_lock.contains(&port) {
```suggestion
    if reuse {
        let mut reused_ports_lock = REUSED_PORTS.lock().unwrap();
        if !reused_ports_lock.contains(&port) {
```

2024-04-06 17:06 UTC, t-nelson commented
ci :pensive: 

lemme guess... now we're running out of ports

2024-04-06 18:07 UTC, HaoranYi commented
> ci 😔
> 
> lemme guess... now we're running out of ports

I think the issue with the test is that we are creating multiple nodes on the same tpu_port for reuse. 
i.e. n1 and n2 will collide on the reuse tpu_port. 
Previously, we were not reusing port. when n2 comes up, it will see that the tpu_port is already used by node1. Then node2 find another port. Everything is good. 
But with multibinding, n2 comes up and sees that tpu_port is used by node_1. But because reuse flag is true, n2 think he can reuse that port. Then the socket is messed up and the test hangs. 

The fix is adding a flag to indicate that we are the first one who bind to a reuse port. And handle it differently than the following reuse port binding. 

I pushed a commit for this change. my local run passed.  
Let's see how it does on the CI.

2025-01-24 22:40 UTC, alexpyattaev commented on net-utils/src/lib.rs
> +lazy_static! {
Are we not doing the same thing that the OS would do for us here? We can always figure out which ports are used by just asking the OS. And it would be far better since we are not the only process using ports.

2025-01-27 23:17 UTC, t-nelson commented
this was superceded by https://github.com/anza-xyz/agave/pull/1452

2025-01-27 23:17 UTC, closed without merging